name: SonarCloud Scan

on: [push, pull_request]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=BiscayN_python-project-83
            -Dsonar.organization=biscayn
            -Dsonar.python.coverage.reportPaths=coverage.xml