name: SonarCloud Scan

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install uv pytest coverage
          make install

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=BiscayN_python-project-83
            -Dsonar.organization=biscayn
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.analysis.autodetection.disabled=true